[package]
name = "bevy_godot4_proc_macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
# bevy_godot4 = { path = "../"}
syn = { version = "2.0.106", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
send_wrapper = "0.6"
heck = "0.5.0"
